spring.application.name=groceries

# Change 'mem' to 'file' so data is saved to a folder
spring.datasource.url=jdbc:h2:file:./data/grocerydb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080


spring.security.user.name=admin
spring.security.user.password=secret123

frontend.url=http://localhost:4200