package com.jivRas.groceries.dto;

import lombok.Data;

/**
 * Request body for POST /api/payments/verify.
 * The frontend sends these three Razorpay identifiers after the user completes payment
 * in the checkout.js modal. The backend verifies the HMAC-SHA256 signature.
 */
@Data
public class VerifyPaymentRequest {

    /** Razorpay order ID — returned by create-order and echoed back by checkout.js. */
    private String razorpayOrderId;

    /** Razorpay payment ID — provided by checkout.js after the user pays. */
    private String razorpayPaymentId;

    /** HMAC-SHA256 signature — generated by Razorpay and passed to the frontend callback. */
    private String razorpaySignature;

    /** JivRas internal order ID — used to locate and confirm the local order record. */
    private Long jivrasOrderId;
}
